/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : wdg_pal1.c
**     Project     : s32k144
**     Processor   : S32K144_100
**     Component   : wdg_pal
**     Version     : Component SDK_S32K14x_09, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_09
**     Compiler    : GNU C Compiler
**     Date/Time   : 2023-04-20, 11:16, # CodeGen: 24
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file wdg_pal1.c
** @version 01.00
*/
/*!
**  @addtogroup wdg_pal1_module wdg_pal1 module documentation
**  @{
*/
#include "wdg_pal1.h"
#include "stddef.h"

/* Serial User Configurations */

/*! @brief User Configurations 0 */
const wdg_config_t wdg_pal1_Config0 =
{
    .clkSource       = WDG_PAL_LPO_CLOCK,
    .opMode          =
    {
        .wait        = false,
        .stop        = false,
        .debug       = true
    },
    .timeoutValue    = 20000,
    .percentWindow   = 100,
    .intEnable       = true,
    .winEnable       = true,
    .prescalerEnable = true,
    .extension       = NULL
};

/* END wdg_pal1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
