/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : wdg_pal1.h
**     Project     : s32k144
**     Processor   : S32K144_100
**     Component   : wdg_pal
**     Version     : Component SDK_S32K14x_09, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_09
**     Compiler    : GNU C Compiler
**     Date/Time   : 2023-04-18, 14:13, # CodeGen: 10
**     Contents    :
**         WDG_Init             - status_t WDG_Init(wdg_instance_t instance, const wdg_config_t * configPtr);
**         WDG_Deinit           - status_t WDG_Deinit(wdg_instance_t instance);
**         WDG_GetDefaultConfig - void WDG_GetDefaultConfig(wdg_config_t * const config);
**         WDG_Refresh          - void WDG_Refresh(wdg_instance_t instance);
**         WDG_SetInt           - status_t WDG_SetInt(wdg_instance_t instance, bool enable);
**         WDG_SetTimeout       - status_t WDG_SetTimeout(wdg_instance_t instance, uint32_t value);
**         WDG_SetWindow        - status_t WDG_SetWindow(uint32_t instance, bool enable, uint32_t Value);
**         WDG_GetCounter       - status_t WDG_GetCounter(wdg_instance_t instance, uint32_t * value);
**         WDG_ClearIntFlag     - void WDG_ClearIntFlag(wdg_instance_t instance);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file wdg_pal1.h
** @version 01.00
*/
/*!
**  @addtogroup wdg_pal1_module wdg_pal1 module documentation
**  @{
*/
#ifndef WDG_PAL1_H
#define WDG_PAL1_H

/* MODULE wdg_pal1. */

/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"


/*! @brief Device instance number */
#define INST_WDG_PAL1    WDG_OVER_WDOG_INSTANCE

/*! @brief Number of user configuration */
#define WDG_PAL1_NUM_OF_USER_CFG    (1U)

/*! @brief Serial module configurations */
extern const wdg_config_t wdg_pal1_Config0;




#endif
/* ifndef WDG_PAL1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

